-d C:\Users\Dudu\Documents\infnet\tp4\verilog_tp4\assessment\impl\gwsynthesis\assessment.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst C:\Users\Dudu\Documents\infnet\tp4\verilog_tp4\assessment\src\dk_video.cst
-cfg C:\Users\Dudu\Documents\infnet\tp4\verilog_tp4\assessment\impl\pnr\device.cfg
-sdc C:\Users\Dudu\Documents\infnet\tp4\verilog_tp4\assessment\src\dk_video.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
